Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -19,6 +19,13 @@ jobs:
         run: npm install
       - name: test
         run: npm run test -- --passWithNoTests --coverage
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: coverage/*.xml    # Path to test results
+          reporter: jest-junit  
       - name: Upload Test Results
         uses: actions/upload-artifact@v4
         with:
